### ISSUE TITLE
关于Autoencoder的问题

### ISSUE THREAD

**Issue by xuetuxiaoqiang** [LMissher/TFMAE#2]
![0478976e-ea9f-40ce-b76c-bf87c9caebc7](https://github.com/user-attachments/assets/a2626a09-6be8-428c-91e5-ec1873d55a5a)
您好！请问这里自编码器为什么一个只使用Decoder一个使用Encoder和Decoder。

**Comment by LMissher** [comment]
你好，文章里IV.B.1里有指出是因为在IDFT后，所有频率已经混在一起，不需要再使用编码器
