### ISSUE TITLE
Model Efficiency Study

### ISSUE THREAD

**Issue by catcatwang** [LMissher/TFMAE#3]
Thank you for your valuable work. For comparison purposes, could you share specific data on training speed and memory usage for each method in the efficiency experiment? You are representing them as graphs in the paper.

**Comment by LMissher** [comment]
Hello, the specific data is shown below:

name = ['DCdetector', 'AnoTran', 'TimesNet', 'TranAD', 'GPT4TS', 'w/o FFT', 'TFMAE']

time = [1439, 600, 961, 371, 857, 2123, 398] S

size = [7211, 6983, 5079, 4807, 14033, 4223, 4129] M

**Comment by catcatwang** [comment]
Okay. Thank you very much.
